name: Auto Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-server
  cancel-in-progress: true

on:
  push:
    branches: [master, 1.23.X, 3.0.0]
  pull_request:
permissions: {}

jobs:
  auto-test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-22.04, windows-latest, ubuntu-22.04-arm]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node: [20, 24]
        # Also test non-LTS, but only on Ubuntu.
        include:
          - os: ubuntu-22.04
            node: 25

    steps:
      - run: git config --global core.autocrlf false # Mainly for Windows
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { persist-credentials: false }

      #    Tempoary disable until we understand TanStack npm supply-chain compromise
      #      - name: Cache/Restore node_modules
      #        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      #        id: node-modules-cache
      #        with:
      #          path: node_modules
      #          key: node-modules-${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}

      # Install latest npm to test the new policy - npm approve-scripts
      - run: npm install npm -g

      # Print the npm version
      - run: npm --version

      - run: npm clean-install --no-fund

      - name: Rebuild native modules for ARM64
        if: matrix.os == 'ubuntu-22.04-arm'
        run: npm rebuild @louislam/sqlite3

      - run: npm run build
      - run: npm run test-backend
        env:
          HEADLESS_TEST: 1
          JUST_FOR_TEST: ${{ secrets.JUST_FOR_TEST }}

  # As a lot of dev dependencies are not supported on ARMv7, we have to test it separately and just test if `npm ci --production` works
  armv7-simple-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { persist-credentials: false }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
        with:
          platforms: linux/arm/v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Test on ARMv7 using Docker with QEMU
        run: |
          docker run --rm --platform linux/arm/v7 \
            -v $PWD:/workspace \
            -w /workspace \
            arm32v7/node:${{ matrix.node }} \
            npm clean-install --no-fund --production

  check-linters:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - run: git config --global core.autocrlf false # Mainly for Windows
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { persist-credentials: false }

      #    Tempoary disable until we understand TanStack npm supply-chain compromise
      #      - name: Cache/Restore node_modules
      #        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      #        id: node-modules-cache
      #        with:
      #          path: node_modules
      #          key: node-modules-${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}

      - name: Use Node.js 20
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 20
      - run: npm clean-install --no-fund
      - run: npm run lint:prod

  e2e-test:
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: read
    env:
      PLAYWRIGHT_VERSION: ~1.39.0
    steps:
      - run: git config --global core.autocrlf false # Mainly for Windows
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with: { persist-credentials: false }

      #    Tempoary disable until we understand TanStack npm supply-chain compromise
      #      - name: Cache/Restore node_modules
      #        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      #        id: node-modules-cache
      #        with:
      #          path: node_modules
      #          key: node-modules-${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22
      - run: npm clean-install --no-fund

      - name: Rebuild native modules for ARM64
        run: npm rebuild @louislam/sqlite3

      - name: Install Playwright ${{ env.PLAYWRIGHT_VERSION }}
        run: npx playwright@${{ env.PLAYWRIGHT_VERSION }} install

      - run: npm run build
      - run: npm run test-e2e
